name: fnol-pilot-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - pandas
      - scikit-learn==1.7.2
      - joblib
      - pyarrow
      - mlflow
      - azureml-mlflow