$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
type: command

code: ../../app/training
command: >-
  python azr_fnol_model_trainer.py --data_path ${{inputs.claims_data}}

inputs:
  claims_data:
    type: uri_file
    path: azureml://datastores/ds_pilot_uploads/paths/fnol_training_dataset.parquet

environment:
  image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04
  conda_file: conda.yml
  
compute: azureml:cpu-cluster
display_name: fnol-pilot-model-training
experiment_name: insurance-risk-experiment