#######################################################
# wf name
#######################################################
name: 'Deploy [Dev] Pilot App' 

#######################################################
# branch
# Trigger only when code is pushed to the main branch
#######################################################
on:
  push:
    branches:
      - main  
    paths:
      - 'app/**'
  workflow_run:
    workflows: ["Deploy [Dev] Pilot Infrastructure"] # This must match the 'name:' field in iac-dev.yml
    types:
      - completed
  workflow_dispatch:

#######################################################
# GitHub Actions request an OIDC token from GitHub 
# and exchange it for Azure access. The workflow must 
# have "id-token: write" to fetch that token
#######################################################
permissions:
  id-token: write
  contents: read
    
#######################################################
# all jobs
#######################################################
jobs:
  ######
  # job 1: 'deploy-infra'
  deploy-app:
    runs-on: ubuntu-latest
    ###################################################
    # all steps
    ###################################################
    steps:
      #########
      # step 1. Checkout the code from your repo
      - name: Checkout Code
        uses: actions/checkout@v4

      #########
      # step 2. Login to Azure using GitHub OIDC federation
      # this is OIDC-style login pattern
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      ###############################################################################################################################
      # upload training data + model training + metrics check + push model 'fnol_model.pkl' to registry
      ###############################################################################################################################
      - name: Upload Data
        run: |
          # Find the storage account in the RG that starts with 'stfnol'
          rg_name=$(jq -r '.parameters.rgname.value' ./iac/env/dev/main.parameters.json)
          st_name=$(az storage account list -g $rg_name --query "[0].name" -o tsv) # first one in list
          container_name='pilot-uploads'
          echo $st_name
          echo $container_name

          #####################################################################
          # assign a role to 'github-actions-sp' for storage account access
          #####################################################################
          # 1. Get the Access Key
          st_key=$(az storage account keys list -g $rg_name -n $st_name --query "[0].value" -o tsv)

          # 2. Use the key (It ignores RBAC propagation)
          az storage blob upload \
            --account-name "$st_name" \
            --account-key "$st_key" \
            --container-name "$container_name" \
            --file app/training/data/fnol_training_dataset.parquet \
            --name paths/fnol_training_dataset.parquet \
            --overwrite

      - name: Run Training Job and evaluate metrics
        id: train_job 
        run: |
                rg_name=$(jq -r '.parameters.rgname.value' ./iac/env/dev/main.parameters.json)
                ml_workspace=$(az ml workspace list -g "$rg_name" --query "[0].name" -o tsv)

                echo "$rg_name"
                echo "$ml_workspace"

                # start train job
                run_id=$(az ml job create \
                --file ./app/training/fnol_model_trainer_config.yml \
                --resource-group "$rg_name" \
                --workspace-name "$ml_workspace" \
                --query name -o tsv)

                echo "RUN_ID=$run_id" >> $GITHUB_ENV
                echo "Created job: $run_id"

                # wait for train job
                # 'az ml job create' returns a Run ID. It does not wait for the model
                # to finish training. Without stream, the GitHub Action would move to 
                # the next step immediately, try to register a model that doesn't exist yet, 
                # and crash.
                az ml job stream \
                --name "$run_id" \
                --resource-group "$rg_name" \
                --workspace-name "$ml_workspace"
                
                # job result
                r2_adj=$(az ml job show --name "$run_id" -g "$rg_name" -w "$ml_workspace" --query "tags.r2_adj" -o tsv)
                echo "$r2_adj"

                if [ "$(echo "$r2_adj < 0.99" | bc -l)" -eq 1 ]; then
                echo "Validation Failed: R2_ADJ is too low ($r2_adj)"
                 exit 1
                fi

      - name: Register model
        if: success()
        run: |
                rg_name=$(jq -r '.parameters.rgname.value' ./iac/env/dev/main.parameters.json)
                ml_workspace=$(az ml workspace list -g "$rg_name" --query "[0].name" -o tsv)

                az ml model create \
                --name "fnol-risk-model" \
                --path "azureml://jobs/${RUN_ID}/outputs/artifacts/outputs/fnol_model.pkl" \
                --type "custom_model" \
                --resource-group "$rg_name" \
                --workspace-name "$ml_workspace"            

      ####################################################
      # ACR: login, download model from aml.model-registry, build docker image, push it to ACR
      # Note: Later, instead of gh action building the Docker image, 
      # the Azure ML Workspace takes over that responsibility.
      ####################################################
      # This uses the identity from step 2 to get a temporary docker token
      - name: Login to ACR, download model from aml.model-registry, build docker image, push it to ACR
        run: |
          RG_NAME=$(jq -r '.parameters.rgname.value' ./iac/env/dev/main.parameters.json)
          # Assuming workspace was discovered in previous steps or via jq
          WORKSPACE=$(az ml workspace list -g "$RG_NAME" --query "[0].name" -o tsv)
          # DOWNLOAD THE MODEL into the ./app context
          # We put it in ./app/model (/fnol-risk-model/model.pkl) so the Dockerfile can COPY it
          mkdir -p ./app/model
          az ml model download --name "fnol-risk-model" \
             --version 1 \
             --download-path ./app/model \
             -g "$RG_NAME" -w "$WORKSPACE"

          # login to ACR
          ACR_NAME=$(jq -r '.parameters.acrName.value' ./iac/env/dev/main.parameters.json)
          az acr login --name $ACR_NAME
          # build docker image
          ACR_REGISTRY="$ACR_NAME.azurecr.io"

          #Get the LATEST version number
          # We query all versions of this model, sort by creation date, and take the top 1
          VERSION_NUM=$(az ml model list --name "fnol-risk-model" \
                -g "$RG_NAME" -w "$WORKSPACE" \
                --query "[0].version" -o tsv)

          echo "Baking Model Version: $VERSION_NUM into Docker image"

          # github.sha is constant for the entire duration of this specific workflow run.
          # ARG = "VERSION_ARG" declared in arg list of docker file
          docker build --build-arg VERSION_ARG="$VERSION_NUM" -t $ACR_REGISTRY/fnol-score:${{ github.sha }} ./app
          # push image to ACR
          docker push $ACR_REGISTRY/fnol-score:${{ github.sha }}
      ####################################################
      # AKS: 
      # login to AKS (credentials) 
      # deploy/update k8s deployment 
      # deploy/update inference service
      ####################################################
      - name: Set AKS Context
        run: |
          # 1. Pull the names again
          RG_NAME=$(jq -r '.parameters.rgname.value' ./iac/env/dev/main.parameters.json)
          AKS_NAME=$(jq -r '.parameters.aksFnolPilotName.value' ./iac/env/dev/main.parameters.json)
            
          # 2. Get credentials using a known stable API version override
          # We manually set the API version to '2024-03-01' which is safe and stable
          az aks get-credentials --resource-group "$RG_NAME" --name "$AKS_NAME" --overwrite-existing      # Verify Connection (Optional but recommended)
      - name: Check AKS Nodes
        run: |
          kubectl get nodes
          kubectl get svc
          kubectl describe pod -l app=fnol-score
      # deploy to AKS    
      - name: Deploy to AKS
        run: |
          # Substitute the image name in manifest and apply: ensures version I just built is the one 
          # that gets deployed:  fnol-score:dev 
          ACR_NAME=$(jq -r '.parameters.acrName.value' ./iac/env/dev/main.parameters.json)

          # 2. Construct the full image path
          FULL_IMAGE_NAME="$ACR_NAME.azurecr.io/fnol-score:${{ github.sha }}"

          # 3. SWAP the placeholder in deployment.yaml for the real path in the file
          # The '|' is used as a delimiter because the image path has slashes
          sed -i "s|__IMAGE__|$FULL_IMAGE_NAME|g" ./app/k8s/deployment.yaml

          # deploy the service
          # This ensures Load Balancer exists
          kubectl apply -f ./app/k8s/service.yaml
          
          # deploy the pods
          kubectl apply -f ./app/k8s/deployment.yaml  

          # pull image from ACR with version "github.sha"
          # substitute ":dev" -> "github.sha"
          # if master notes a change in the sha, it replaces the old pod with a new one 
          # running the image with the new sha
          kubectl set image deployment/fnol-score-deployment fnol-score-container=$ACR_NAME.azurecr.io/fnol-score:${{ github.sha }}

