#######################################################
# wf name
#######################################################
name: 'Deploy [Dev] Pilot App' 

#######################################################
# branch
# Trigger only when code is pushed to the main branch
#######################################################
on:
  push:
    branches:
      - main  
    paths:
      - 'app/**'
  workflow_run:
    workflows: ["Deploy [Dev] Pilot Infrastructure"] # This must match the 'name:' field in iac-dev.yml
    types:
      - completed
  workflow_dispatch:

#######################################################
# GitHub Actions request an OIDC token from GitHub 
# and exchange it for Azure access. The workflow must 
# have "id-token: write" to fetch that token
#######################################################
permissions:
  id-token: write
  contents: read
    
#######################################################
# all jobs
#######################################################
jobs:
  ######
  # job 1: 'deploy-infra'
  deploy-infra:
    runs-on: ubuntu-latest
    ###################################################
    # all steps
    ###################################################
    steps:
      #########
      # step 1. Checkout the code from your repo
      - name: Checkout Code
        uses: actions/checkout@v4

      #########
      # step 2. Login to Azure using GitHub OIDC federation
      # this is OIDC-style login pattern
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      ####################################################
      # ACR: login, build docker image, push it to ACR
      ####################################################
      # This uses the identity from step 2 to get a temporary docker token
      - name: Login to ACR, build docker image, push it to ACR
        run: |
          # login
          ACR_NAME=$(jq -r '.parameters.acrName.value' ./iac/env/dev/main.parameters.json)
          az acr login --name $ACR_NAME
          # build docker image
          ACR_REGISTRY="$ACR_NAME.azurecr.io"
          # github.sha is constant for the entire duration of this specific workflow run.
          docker build -t $ACR_REGISTRY/fnol-score:${{ github.sha }} ./app
          # push image to ACR
          docker push $ACR_REGISTRY/fnol-score:${{ github.sha }}

      ####################################################
      # AKS: 
      # login to AKS (credentials) 
      # deploy/update k8s deployment 
      # deploy/update inference service
      ####################################################
      - name: Set AKS Context
        run: |
          # 1. Pull the names again
          RG_NAME=$(jq -r '.parameters.rgname.value' ./iac/env/dev/main.parameters.json)
          AKS_NAME=$(jq -r '.parameters.aksFnolPilotName.value' ./iac/env/dev/main.parameters.json)
            
          # 2. Get credentials using a known stable API version override
          # We manually set the API version to '2024-03-01' which is safe and stable
          az aks get-credentials --resource-group "$RG_NAME" --name "$AKS_NAME" --overwrite-existing      # Verify Connection (Optional but recommended)
      - name: Check AKS Nodes
        run: |
          kubectl get nodes
          kubectl get svc
          kubectl describe pod -l app=fnol-score
      # deploy to AKS    
      - name: Deploy to AKS
        run: |
          # Substitute the image name in manifest and apply: ensures version I just built is the one 
          # that gets deployed:  fnol-score:dev 
          ACR_NAME=$(jq -r '.parameters.acrName.value' ./iac/env/dev/main.parameters.json)

          # 2. Construct the full image path
          FULL_IMAGE_NAME="$ACR_NAME.azurecr.io/fnol-score:${{ github.sha }}"

          # 3. SWAP the placeholder in deployment.yaml for the real path in the file
          # The '|' is used as a delimiter because the image path has slashes
          sed -i "s|__IMAGE__|$FULL_IMAGE_NAME|g" ./app/k8s/deployment.yaml

          # deploy the service
          # This ensures Load Balancer exists
          kubectl apply -f ./app/k8s/service.yaml
          
          # deploy the pods
          kubectl apply -f ./app/k8s/deployment.yaml  

          # pull image from ACR with version "github.sha"
          # substitute ":dev" -> "github.sha"
          # if master notes a change in the sha, it replaces the old pod with a new one 
          # running the image with the new sha
          kubectl set image deployment/fnol-score-deployment fnol-score-container=$ACR_NAME.azurecr.io/fnol-score:${{ github.sha }}
      
