name: "Destroy Dev Infrastructure (Freeze All Costs)"

on:
  workflow_dispatch: # Manual trigger only

permissions:
  id-token: write
  contents: read

jobs:
  # job 1  
  destroy:
    runs-on: ubuntu-latest
    steps:
      # step 1
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # checkout step
      - name: Checkout Code
        uses: actions/checkout@v4

      # step 2 
      - name: Read resource group name from parameters
        id: params
        run: |
            RG_NAME=$(jq -r '.parameters.rgname.value' ./iac/env/dev/main.parameters.json)
            echo "rg_name=$RG_NAME" >> $GITHUB_OUTPUT
      # step 3
      - name: Delete Resource Group
        run: |
            echo "Deleting Resource Group ..."
            az group delete \
            --name "${{ steps.params.outputs.rgname }}" \
            --yes \
            --no-wait

      - name: Purge Key Vault (Cleanup Ghost)
        if: steps.params.outputs.keyVaultName != '' 
        run: |
          echo "Purging Key Vault to release global name..."
          # We use continue-on-error because if it's already purged, we don't want the build to fail
          az keyvault purge --name "${{ steps.params.outputs.keyVaultName }}" || echo "Vault not found or already purged."

      - name: Purge AML Workspace (Stop Meta-Costs)
        if: steps.params.outputs.amlWorkspaceNameOut != ''
        run: |
          echo "Permanently deleting AML Workspace..."
          # Using the ML extension to ensure a hard delete
          az ml workspace delete --name "${{ steps.params.outputs.amlWorkspaceNameOut }}" \
            --resource-group "${{ steps.params.outputs.rgname }}" \
            --permanently-delete --yes || echo "AML Workspace already gone."
